# Generated by Django 4.1.2 on 2022-10-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catg_paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarjetaIden', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEnvios', models.BigIntegerField(max_length=50)),
                ('cantidad', models.IntegerField(max_length=30)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaquete', models.IntegerField(max_length=50)),
                ('precio', models.BigIntegerField()),
                ('FKcategoria_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWproyectoApp.catg_paquete')),
                ('FKenvios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWproyectoApp.envios')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFactura', models.IntegerField(max_length=30)),
                ('fecha', models.DateField()),
                ('clienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWproyectoApp.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='envios',
            name='FKfactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWproyectoApp.factura'),
        ),
        migrations.CreateModel(
            name='cuenta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Tarjeta', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=45)),
                ('FKcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWproyectoApp.cliente')),
            ],
        ),
    ]
