# Generated by Django 4.1.2 on 2022-10-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWproyectoApp', '0002_alter_cliente_telefono_alter_envios_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='TarjetaIden',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
