# Generated by Django 4.1.2 on 2022-10-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWproyectoApp', '0004_alter_cliente_tarjetaiden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='idEnvios',
            field=models.TextField(max_length=10),
        ),
    ]
