# Generated by Django 4.1.2 on 2022-10-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWproyectoApp', '0005_alter_envios_idenvios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='idEnvios',
            field=models.CharField(max_length=10),
        ),
    ]
