# Generated by Django 4.1.2 on 2022-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWproyectoApp', '0006_alter_envios_idenvios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catg_paquete',
            name='idCategoria',
            field=models.CharField(max_length=10),
        ),
    ]
